"""Create the M4 shared platform tables.

Revision ID: 0002_m4_platform
Revises: 0001_extensions
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0002_m4_platform"
down_revision: str | None = "0001_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.Enum("USER", "SUPPLIER", "SYSTEM", name="audit_actor_type"), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_name", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_action", "audit_events", ["action"], unique=False)
    op.create_index("ix_audit_actor", "audit_events", ["actor_type", "actor_id"], unique=False)
    op.create_index("ix_audit_aggregate", "audit_events", ["aggregate_type", "aggregate_id"], unique=False)
    op.create_index(op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False)
    op.create_index(op.f("ix_audit_events_tenant_id"), "audit_events", ["tenant_id"], unique=False)
    op.create_index("ix_audit_tenant_created", "audit_events", ["tenant_id", "created_at"], unique=False)
    op.create_table(
        "file_upload_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("part_size_bytes", sa.Integer(), nullable=False),
        sa.Column("total_parts", sa.Integer(), nullable=False),
        sa.Column("uploaded_parts", postgresql.JSONB(astext_type=Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "UPLOADING",
                "VERIFYING",
                "SCANNING",
                "COMPLETED",
                "CANCELLED",
                "FAILED",
                name="upload_status",
            ),
            nullable=False,
        ),
        sa.Column("scan_status", sa.Enum("PENDING", "CLEAN", "INFECTED", "FAILED", name="scan_status"), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("minio_object_key", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_upload_sessions_tenant_id"), "file_upload_sessions", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_file_upload_sessions_user_id"), "file_upload_sessions", ["user_id"], unique=False)
    op.create_index("ix_sessions_expires", "file_upload_sessions", ["expires_at"], unique=False)
    op.create_index("ix_sessions_user_status", "file_upload_sessions", ["user_id", "status"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uploader_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("minio_bucket", sa.String(length=100), nullable=False),
        sa.Column("minio_object_key", sa.String(length=500), nullable=False),
        sa.Column("scan_status", sa.Enum("PENDING", "CLEAN", "INFECTED", "FAILED", name="scan_status"), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_files_resource", "files", ["resource_type", "resource_id"], unique=False)
    op.create_index(op.f("ix_files_sha256"), "files", ["sha256"], unique=False)
    op.create_index(op.f("ix_files_tenant_id"), "files", ["tenant_id"], unique=False)
    op.create_index("ix_files_tenant_purpose", "files", ["tenant_id", "purpose"], unique=False)
    op.create_index(op.f("ix_files_uploader_id"), "files", ["uploader_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "FILE_SCAN", "FILE_IMPORT", "DOCUMENT_GENERATION", "AI_ANALYSIS", "EXPORT", "OTHER", name="job_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "CANCELLED", name="job_status"),
            nullable=False,
        ),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.String(length=255), nullable=True),
        sa.Column("input_data", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_celery_task_id"), "jobs", ["celery_task_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_tenant_created", "jobs", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_tenant_id"), "jobs", ["tenant_id"], unique=False)
    op.create_index("ix_jobs_tenant_status", "jobs", ["tenant_id", "status"], unique=False)
    op.create_index("ix_jobs_user_status", "jobs", ["user_id", "status"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SYSTEM", "TASK", "REVIEW", "APPROVAL", "MESSAGE", "ASSIGNMENT", name="notification_type"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("extra_data", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_notifications_tenant_created", "notifications", ["tenant_id", "created_at"], unique=False)
    op.create_index(op.f("ix_notifications_tenant_id"), "notifications", ["tenant_id"], unique=False)
    op.create_index("ix_notifications_user_unread", "notifications", ["user_id", "is_read"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("role", sa.Enum("ADMIN", "PROJECT_LEAD", "MEMBER", "REVIEWER", name="user_role"), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("status", sa.Enum("INVITED", "ACTIVE", "DISABLED", name="user_status"), nullable=False),
        sa.Column("is_super_admin", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_index("ix_users_tenant_email", "users", ["tenant_id", "email"], unique=True)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index("ix_users_tenant_status", "users", ["tenant_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_tenant_status", table_name="users")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index("ix_users_tenant_email", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_notifications_user_unread", table_name="notifications")
    op.drop_index(op.f("ix_notifications_tenant_id"), table_name="notifications")
    op.drop_index("ix_notifications_tenant_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_jobs_user_status", table_name="jobs")
    op.drop_index("ix_jobs_tenant_status", table_name="jobs")
    op.drop_index(op.f("ix_jobs_tenant_id"), table_name="jobs")
    op.drop_index("ix_jobs_tenant_created", table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_celery_task_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_files_uploader_id"), table_name="files")
    op.drop_index("ix_files_tenant_purpose", table_name="files")
    op.drop_index(op.f("ix_files_tenant_id"), table_name="files")
    op.drop_index(op.f("ix_files_sha256"), table_name="files")
    op.drop_index("ix_files_resource", table_name="files")
    op.drop_table("files")
    op.drop_index("ix_sessions_user_status", table_name="file_upload_sessions")
    op.drop_index("ix_sessions_expires", table_name="file_upload_sessions")
    op.drop_index(op.f("ix_file_upload_sessions_user_id"), table_name="file_upload_sessions")
    op.drop_index(op.f("ix_file_upload_sessions_tenant_id"), table_name="file_upload_sessions")
    op.drop_table("file_upload_sessions")
    op.drop_index("ix_audit_tenant_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_tenant_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index("ix_audit_aggregate", table_name="audit_events")
    op.drop_index("ix_audit_actor", table_name="audit_events")
    op.drop_index("ix_audit_action", table_name="audit_events")
    op.drop_table("audit_events")
    for enum_name in (
        "user_status",
        "user_role",
        "notification_type",
        "job_status",
        "job_type",
        "scan_status",
        "upload_status",
        "audit_actor_type",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
