"""create M5 bid document and library tables

Revision ID: 0004_m5_bids
Revises: 0003_m6_evaluation
Create Date: 2026-08-11 00:22:13.547595
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_m5_bids"
down_revision: str | None = "0003_m6_evaluation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bid_idempotency",
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index("ix_bid_idempotency_tenant", "bid_idempotency", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_bid_idempotency_tenant_id"), "bid_idempotency", ["tenant_id"], unique=False)
    op.create_table(
        "bid_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("tender_no", sa.String(length=128), nullable=False),
        sa.Column("tender_entity", sa.String(length=255), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.String(length=36), nullable=False),
        sa.Column("assignee_name", sa.String(length=128), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tender_file_id", sa.String(length=36), nullable=True),
        sa.Column("tender_file_name", sa.String(length=255), nullable=True),
        sa.Column("tender_mime_type", sa.String(length=128), nullable=True),
        sa.Column("tender_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("tender_sha256", sa.String(length=64), nullable=True),
        sa.Column("tender_scan_status", sa.String(length=16), nullable=True),
        sa.Column("tender_file_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tender_preview_url", sa.Text(), nullable=True),
        sa.Column("tender_download_url", sa.Text(), nullable=True),
        sa.Column("linked_evaluation_id", sa.String(length=36), nullable=True),
        sa.Column("archived_reason", sa.Text(), nullable=True),
        sa.Column("failed_stage", sa.String(length=32), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bid_tasks_tenant_assignee", "bid_tasks", ["tenant_id", "assignee_id"], unique=False)
    op.create_index("ix_bid_tasks_tenant_deadline", "bid_tasks", ["tenant_id", "deadline"], unique=False)
    op.create_index(op.f("ix_bid_tasks_tenant_id"), "bid_tasks", ["tenant_id"], unique=False)
    op.create_index("ix_bid_tasks_tenant_status", "bid_tasks", ["tenant_id", "status"], unique=False)
    op.create_table(
        "fragments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("source_file_id", sa.String(length=128), nullable=True),
        sa.Column("source_file_snapshot", sa.JSON(), nullable=True),
        sa.Column("document_version", sa.String(length=128), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_fragments_tenant_category", "fragments", ["tenant_id", "category"], unique=False)
    op.create_index("ix_fragments_tenant_deleted", "fragments", ["tenant_id", "deleted_at"], unique=False)
    op.create_table(
        "qualification_import_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("actor_name", sa.String(length=255), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "file_id", name="uq_qualification_import_tenant_file"),
        sa.UniqueConstraint("tenant_id", "job_id", name="uq_qualification_import_tenant_job"),
    )
    op.create_index(
        op.f("ix_qualification_import_jobs_tenant_id"), "qualification_import_jobs", ["tenant_id"], unique=False
    )
    op.create_table(
        "qualifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("cert_number", sa.String(length=128), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("document_version", sa.String(length=64), nullable=False),
        sa.Column("reminder_days", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=36), nullable=True),
        sa.Column("deleted_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "cert_number", name="uq_qualifications_tenant_cert"),
    )
    op.create_index("ix_qualifications_tenant_category", "qualifications", ["tenant_id", "category"], unique=False)
    op.create_index("ix_qualifications_tenant_deleted", "qualifications", ["tenant_id", "deleted_at"], unique=False)
    op.create_index("ix_qualifications_tenant_expiry", "qualifications", ["tenant_id", "expiry_date"], unique=False)
    op.create_index(op.f("ix_qualifications_tenant_id"), "qualifications", ["tenant_id"], unique=False)
    op.create_table(
        "bid_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("latest_file_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bid_documents_tenant_id"), "bid_documents", ["tenant_id"], unique=False)
    op.create_index("ix_bid_documents_tenant_task", "bid_documents", ["tenant_id", "task_id"], unique=False)
    op.create_table(
        "bid_job_bindings",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_bid_job_bindings_task_id"), "bid_job_bindings", ["task_id"], unique=False)
    op.create_index(op.f("ix_bid_job_bindings_tenant_id"), "bid_job_bindings", ["tenant_id"], unique=False)
    op.create_index("ix_bid_job_bindings_tenant_task", "bid_job_bindings", ["tenant_id", "task_id"], unique=False)
    op.create_table(
        "bid_materials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("requirement", sa.Text(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=True),
        sa.Column("match_confidence", sa.Float(), nullable=True),
        sa.Column("file_id", sa.String(length=36), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=128), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("file_scan_status", sa.String(length=16), nullable=True),
        sa.Column("file_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_preview_url", sa.Text(), nullable=True),
        sa.Column("file_download_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bid_materials_tenant_id"), "bid_materials", ["tenant_id"], unique=False)
    op.create_index(
        "ix_bid_materials_tenant_task", "bid_materials", ["tenant_id", "task_id", "sort_order"], unique=False
    )
    op.create_table(
        "bid_review_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bid_review_reports_tenant_id"), "bid_review_reports", ["tenant_id"], unique=False)
    op.create_index(
        "ix_bid_review_reports_tenant_task", "bid_review_reports", ["tenant_id", "task_id", "created_at"], unique=False
    )
    op.create_table(
        "bid_task_assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("user_name", sa.String(length=128), nullable=False),
        sa.Column("role_in_task", sa.String(length=16), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "user_id", name="uq_bid_task_assignment"),
    )
    op.create_index("ix_bid_task_assignments_tenant", "bid_task_assignments", ["tenant_id", "task_id"], unique=False)
    op.create_index(op.f("ix_bid_task_assignments_tenant_id"), "bid_task_assignments", ["tenant_id"], unique=False)
    op.create_table(
        "bid_tender_requirements",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("project_info", sa.JSON(), nullable=False),
        sa.Column("scoring_items", sa.JSON(), nullable=False),
        sa.Column("disqualification_items", sa.JSON(), nullable=False),
        sa.Column("qualification_requirements", sa.JSON(), nullable=False),
        sa.Column("technical_requirements", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_index(
        "ix_bid_tender_requirements_tenant", "bid_tender_requirements", ["tenant_id", "task_id"], unique=False
    )
    op.create_index(
        op.f("ix_bid_tender_requirements_tenant_id"), "bid_tender_requirements", ["tenant_id"], unique=False
    )
    op.create_table(
        "fragment_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("fragment_id", sa.String(length=36), nullable=False),
        sa.Column("bid_task_id", sa.String(length=128), nullable=False),
        sa.Column("material_id", sa.String(length=128), nullable=True),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fragment_id"],
            ["fragments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_fragment_references_tenant_bid", "fragment_references", ["tenant_id", "bid_task_id"], unique=False
    )
    op.create_index(
        "ix_fragment_references_tenant_fragment", "fragment_references", ["tenant_id", "fragment_id"], unique=False
    )
    op.create_table(
        "fragment_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("fragment_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("document_version", sa.String(length=128), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=False),
        sa.Column("source_file_id", sa.String(length=128), nullable=True),
        sa.Column("source_file_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_by_id", sa.String(length=128), nullable=False),
        sa.Column("created_by_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fragment_id"],
            ["fragments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fragment_id", "version_number", name="uq_fragment_version_number"),
    )
    op.create_index(
        "ix_fragment_versions_tenant_fragment", "fragment_versions", ["tenant_id", "fragment_id"], unique=False
    )
    op.create_table(
        "qualification_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("qualification_id", sa.String(length=36), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("document_version", sa.String(length=64), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["qualification_id"],
            ["qualifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qualification_versions_tenant_id"), "qualification_versions", ["tenant_id"], unique=False)
    op.create_index(
        "ix_qualification_versions_tenant_qualification",
        "qualification_versions",
        ["tenant_id", "qualification_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "bid_document_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("source_version_id", sa.String(length=36), nullable=True),
        sa.Column("roll_back", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("created_by_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["bid_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["bid_document_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "version_number", name="uq_bid_document_version_number"),
    )
    op.create_index(
        "ix_bid_document_versions_tenant_doc", "bid_document_versions", ["tenant_id", "document_id"], unique=False
    )
    op.create_index(op.f("ix_bid_document_versions_tenant_id"), "bid_document_versions", ["tenant_id"], unique=False)
    op.create_table(
        "bid_review_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("suggestion", sa.Text(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("decision_comment", sa.Text(), nullable=True),
        sa.Column("decided_by_id", sa.String(length=36), nullable=True),
        sa.Column("decided_by_name", sa.String(length=128), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["bid_review_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bid_tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bid_review_findings_tenant_id"), "bid_review_findings", ["tenant_id"], unique=False)
    op.create_index(
        "ix_bid_review_findings_tenant_task",
        "bid_review_findings",
        ["tenant_id", "task_id", "severity", "decision"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bid_review_findings_tenant_task", table_name="bid_review_findings")
    op.drop_index(op.f("ix_bid_review_findings_tenant_id"), table_name="bid_review_findings")
    op.drop_table("bid_review_findings")
    op.drop_index(op.f("ix_bid_document_versions_tenant_id"), table_name="bid_document_versions")
    op.drop_index("ix_bid_document_versions_tenant_doc", table_name="bid_document_versions")
    op.drop_table("bid_document_versions")
    op.drop_index("ix_qualification_versions_tenant_qualification", table_name="qualification_versions")
    op.drop_index(op.f("ix_qualification_versions_tenant_id"), table_name="qualification_versions")
    op.drop_table("qualification_versions")
    op.drop_index("ix_fragment_versions_tenant_fragment", table_name="fragment_versions")
    op.drop_table("fragment_versions")
    op.drop_index("ix_fragment_references_tenant_fragment", table_name="fragment_references")
    op.drop_index("ix_fragment_references_tenant_bid", table_name="fragment_references")
    op.drop_table("fragment_references")
    op.drop_index(op.f("ix_bid_tender_requirements_tenant_id"), table_name="bid_tender_requirements")
    op.drop_index("ix_bid_tender_requirements_tenant", table_name="bid_tender_requirements")
    op.drop_table("bid_tender_requirements")
    op.drop_index(op.f("ix_bid_task_assignments_tenant_id"), table_name="bid_task_assignments")
    op.drop_index("ix_bid_task_assignments_tenant", table_name="bid_task_assignments")
    op.drop_table("bid_task_assignments")
    op.drop_index("ix_bid_review_reports_tenant_task", table_name="bid_review_reports")
    op.drop_index(op.f("ix_bid_review_reports_tenant_id"), table_name="bid_review_reports")
    op.drop_table("bid_review_reports")
    op.drop_index("ix_bid_materials_tenant_task", table_name="bid_materials")
    op.drop_index(op.f("ix_bid_materials_tenant_id"), table_name="bid_materials")
    op.drop_table("bid_materials")
    op.drop_index("ix_bid_job_bindings_tenant_task", table_name="bid_job_bindings")
    op.drop_index(op.f("ix_bid_job_bindings_tenant_id"), table_name="bid_job_bindings")
    op.drop_index(op.f("ix_bid_job_bindings_task_id"), table_name="bid_job_bindings")
    op.drop_table("bid_job_bindings")
    op.drop_index("ix_bid_documents_tenant_task", table_name="bid_documents")
    op.drop_index(op.f("ix_bid_documents_tenant_id"), table_name="bid_documents")
    op.drop_table("bid_documents")
    op.drop_index(op.f("ix_qualifications_tenant_id"), table_name="qualifications")
    op.drop_index("ix_qualifications_tenant_expiry", table_name="qualifications")
    op.drop_index("ix_qualifications_tenant_deleted", table_name="qualifications")
    op.drop_index("ix_qualifications_tenant_category", table_name="qualifications")
    op.drop_table("qualifications")
    op.drop_index(op.f("ix_qualification_import_jobs_tenant_id"), table_name="qualification_import_jobs")
    op.drop_table("qualification_import_jobs")
    op.drop_index("ix_fragments_tenant_deleted", table_name="fragments")
    op.drop_index("ix_fragments_tenant_category", table_name="fragments")
    op.drop_table("fragments")
    op.drop_index("ix_bid_tasks_tenant_status", table_name="bid_tasks")
    op.drop_index(op.f("ix_bid_tasks_tenant_id"), table_name="bid_tasks")
    op.drop_index("ix_bid_tasks_tenant_deadline", table_name="bid_tasks")
    op.drop_index("ix_bid_tasks_tenant_assignee", table_name="bid_tasks")
    op.drop_table("bid_tasks")
    op.drop_index(op.f("ix_bid_idempotency_tenant_id"), table_name="bid_idempotency")
    op.drop_index("ix_bid_idempotency_tenant", table_name="bid_idempotency")
    op.drop_table("bid_idempotency")
    # ### end Alembic commands ###
